In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sk
from numpy import random 
#Author: Vinay Maruri, email: vmaruri1@berkeley.edu

In [2]:
#First off is Building Coding Intuition!!:

In [3]:
#https://cs61a.org/lab/lab01/ (open)
#credits: CS61A course staff and instructors (used for educational purposes)

In [ ]:
#Write a function below that computes whether or not a given digit has adjacent 8's
#return true/false.
def double_eights(n):
    #write code here

In [ ]:
#now can you right the same thing recursively?
#return true/false.
#assume that boo is initialized to none.
def double_eightsrecur(n, boo):
    #write code here

In [ ]:
#Tests to verify if your functions work properly (you should pass all)

In [ ]:
print(double_eights(888))

In [ ]:
print(double_eights(129031832912889090019230))

In [ ]:
print(double_eights(8))

In [ ]:
print(double_eightsrecur(88, None))

In [ ]:
print(double_eightsrecur(88, None))

In [ ]:
print(double_eightsrecur(8, None))

In [ ]:
print(double_eightsrecur(129031832912889090019230, None))

In [4]:
#numpy is Python's big mathematics library

In [5]:
data = np.array([1,2,3,4,5,6,7,8,9]) # right
print(data)

#Creating a nice basic array.

[1 2 3 4 5 6 7 8 9]


In [6]:
data = np.array(range (1000))
print(data)
#Create big array.

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [7]:
data[2]
#indexing into an array.

2

In [8]:
data[0:5]
#slicing into an array

array([0, 1, 2, 3, 4])

In [9]:
#livecode example of skipping elements

In [10]:
#Arrays use much less memory than lists. Please use arrays whenever possible for efficiency.

In [12]:
#Numpy's math functions: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html
#please see documentation for full list of all available operations.

In [13]:
#sum example
a = np.array(range(1000))
b = np.array(range(100))
c = np.sum(a)
d = np.sum(b)
e = c+d
print(e)

504450


In [14]:
np.log(a)
#log example

C:\Users\EndlessWormhole\Anaconda3\envs\data100\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898,
        2.99573227,  3.04452244,  3.09104245,  3.13549422,  3.17805383,
        3.21887582,  3.25809654,  3.29583687,  3.33220451,  3.36729583,
        3.40119738,  3.4339872 ,  3.4657359 ,  3.49650756,  3.52636052,
        3.55534806,  3.58351894,  3.61091791,  3.63758616,  3.66356165,
        3.68887945,  3.71357207,  3.73766962,  3.76120012,  3.78418963,
        3.80666249,  3.8286414 ,  3.8501476 ,  3.87120101,  3.8918203 ,
        3.91202301,  3.93182563,  3.95124372,  3.97029191,  3.98898405,
        4.00733319,  4.02535169,  4.04305127,  4.06044301,  4.07753744,
        4.09434456,  4.11087386,  4.12713439,  4.14313473,  4.15888308,
        4.17438727,  4.18965474,  4.20469262,  4.21950771,  4.23

In [15]:
d = [x for x in range(1000)]
#list comprehension syntax---will cover later.

In [16]:
np.add(a, d)
#adding example

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

$\sum_{i = 0}^{n} tan(x_i^{2})$ for all $x_i$'s in X. 

I would like to compute this formula. Oh no!!! Python to the rescue!!

In [17]:
complicated = np.sum(np.tan(np.square(d)))
complicated
#This is called "currying" in computer science. Read this to learn more: https://en.wikipedia.org/wiki/Currying

-8363.4561627564162

In [18]:
np.average(d)
#average of an array.

499.5

In [19]:
np.median(d)
#median of an array.

499.5

In [20]:
np.nanmax(d)
#maximum of array (not including NaN's)

999

In [21]:
np.nanstd(d)
#std dev of array (not including NaN's)

288.67499025720952

In [22]:
np.inner(a, d)
#numpy supports inner products.

332833500

In [23]:
np.dot(a, d)

332833500

In [24]:
np.outer(a, d)
#outer products

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    997,    998,    999],
       [     0,      2,      4, ...,   1994,   1996,   1998],
       ..., 
       [     0,    997,   1994, ..., 994009, 995006, 996003],
       [     0,    998,   1996, ..., 995006, 996004, 997002],
       [     0,    999,   1998, ..., 996003, 997002, 998001]])

In [25]:
#read more on numpy's linear algebra library here: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

In [28]:
np.random.randn()
#picks a random sample from the normal distribution.

0.7966484303508704

In [ ]:
np.random.randint(0, 100)
#returns a random integer from 0 to 100 inclusive.

In [ ]:
np.random.uniform(0, 100, 5)
#returns a random sample from uniform distribution of size 5 where low is 0 and high is 100.

In [ ]:
#more on random sampling in numpy here: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

In [ ]:
#next up: Pandas!!! (unfortunately a lot more icky to work with) (Python's big data analysis library)

In [ ]:
anne = pd.read_excel('Anne.xls')
#Dataset taken from Economics 121, Industrial Organization and Public Policy, Fall 2018, Homework 2.
#We are reading in an excel file and converting it into a pandas dataframe object. This is a tabular, 2-D data structure
#similar to a matrix (linear algebra) with rows and columns.

In [ ]:
anne

In [ ]:
anne['price ($)'].max()
#What is the maximum price somebody paid for Anne's chocolates?

In [ ]:
anne['price ($)'].min()
#What is the minimum price somebody paid for Anne's chocolates?

In [ ]:
plt.figure(figsize = (10,5))

newdf0 = anne.loc[anne['dayofweek'] == 0]
ax = sns.lineplot(x = anne['price ($)'], y = anne['Buy (1=buy, 0=not buy)'], data = newdf0, ci = None)
plt.title("Propensity to buy vs Price for Anne's chocolates (Monday)")

#demand curve for anne's chocolates on Monday.

In [ ]:
plt.figure(figsize = (10,5))
newdf1 = anne.loc[anne['dayofweek'] == 1]
ay = sns.lineplot(x = anne['price ($)'], y = anne['Buy (1=buy, 0=not buy)'], data = newdf1, ci = None)
plt.title("Propensity to buy vs Price for Anne's chocolates (Tuesday)")

In [ ]:
plt.figure(figsize = (10,5))

ax = sns.lineplot(x = anne['price ($)'], y = anne['Buy (1=buy, 0=not buy)'], data = anne)

plt.title("Propensity to buy vs Price for Anne's chocolates (aggregated)")

#This is a line plot of Propensity to buy vs Price for Anne's chocolates, with all price and buy data aggregated, 
#and not separated by day of week.
#Also includes a 95% confidence interval conveniently.

In [ ]:
anne['dayofweek'] = anne['dayofweek'].map({'Mon': 0, 'Tue': 1, 'Wed': 2, 'Thu': 3, 'Fri': 4, 'Sat': 5, 'Sun': 6})
#convert strings to numbers

In [ ]:
anne

In [ ]:
anne['dayofweek'].isnull()
#check for missing values

In [ ]:
anne.groupby('dayofweek').agg('min')
#Key function of pandas is filter/groupby/agg---this allows you to combine, get finer/larger granularity in data, as well as keep/drop data that you may not want.

In [ ]:
anne.groupby('dayofweek').agg({'price ($)': 'max'})
#we can also aggregate only on specific columns of interest.

In [2]:
from sklearn.linear_model import LinearRegression
# Linear Regression in python
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)

In [3]:
reg.score(X, y)

1.0

In [4]:
reg.coef_

array([1., 2.])

In [5]:
reg.intercept_ 

3.0000000000000018

In [6]:
reg.predict(np.array([[3, 5]]))

array([16.])

In [7]:
from sklearn.linear_model import LogisticRegression
X = np.array(object = anne['mobile (1=mobile, 0=not)'][0:50]).reshape(-1, 1)
y = np.array(object = anne['price ($)'][0:50]).reshape(-1,1)
logit = LogisticRegression()
model = logit.fit(y, X)
#naive implementation of logistic regression model---I am creating training data by simply taking the first 50 entries in price and mobile columns
#I will discuss why this is bad.

NameError: name 'anne' is not defined

In [ ]:
model.predict(np.array(object = anne['price ($)'][50:]).reshape(-1,1))
#Any guesses on output?

In [ ]:
#confirmation of our result and intuition

In [ ]:
sns.boxplot(x = np.array(object = anne['mobile (1=mobile, 0=not)'][50:]), y = np.array(object = anne['price ($)'][50:]))